### ISSUE TITLE
otus_97.sh fails when clustering output fasta file is too large

### ISSUE THREAD

**Issue by daniclaar** [jrcunning/SymITS2#1]
When processing my full data set (384 samples), otus_97.sh fails with the following error:
`awk: program limit exceeded: maximum number of fields size=32767
	FILENAME="data/otus_97/combined_seqs_trimmed_otus.txt" FNR=1505 NR=150`

Can easily be fixed by installing gawk on your machine, and editing the script accordingly to 
`gawk '$3 ~ /./ {print}' data/otus_97/combined_seqs_trimmed_otus.txt > data/otus_97/nosingles_otus.txt
` 

Let me know if you'd like me to edit and push with this change :)

**Comment by jrcunning** [comment]
Yes please thanks for the fix!

**Comment by daniclaar** [comment]
Fixed with commit cd51b67
